#spring:
#  datasource:
#    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:wallets}
#    username: ${DB_USER:wallet}
#    password: ${DB_PASSWORD:changeme}
#    
##    username: postgres
##    password: admin
#    
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: ${DB_POOL_MAX:10}
#  jpa:
#    hibernate:
#      ddl-auto: none   # миграции выполняет Liquibase
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yaml
#    contexts: ${LIQUIBASE_CONTEXTS:}
#
#server:
#  port: ${APP_PORT:8080}


#spring:
#  datasource:
#    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:wallets}
#    username: ${DB_USER:postgres}
#    password: ${DB_PASSWORD:admin}
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: ${DB_POOL_MAX:10}
#
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yaml
#    contexts: ${LIQUIBASE_CONTEXTS:}
#
#server:
#  port: ${APP_PORT:8080}


#spring:
#  profiles:
#    active: ${SPRING_PROFILES_ACTIVE:local}
#
#  datasource:
#    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:wallets}
#    username: ${DB_USER:wallet}
#    password: ${DB_PASSWORD:changeme}
#    driver-class-name: org.postgresql.Driver
#
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yaml
#
#server:
#  port: ${APP_PORT:8080}


#spring:
#  datasource:
#    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:wallets}
##    username: ${DB_USER:postgres}
##    password: ${DB_PASSWORD:admin}
#    
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: ${DB_POOL_MAX:10}
#
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yaml
#    contexts: ${LIQUIBASE_CONTEXTS:}
#
#server:
#  port: ${APP_PORT:8080}


spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_MAX:10}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: ${LIQUIBASE_CONTEXTS:}

server:
  port: ${APP_PORT:8080}